name: Download workflow artifact
description: Download and extract an artifact associated with given workflow and commit
author: dawidd6
branding:
  icon: download
  color: blue
inputs:
  github_token:
    description: Github token
    required: true
  workflow:
    description: Workflow name
    required: true
  owner:
    description: Repository owner (defaults to current repo owner)
    required: false
  repo:
    description: Repository name (defaults to current repo name)
    required: false
  pr:
    description: Pull request number
    required: false
  commit:
    description: Commit SHA1
    required: false
  name:
    description: Artifact name
    required: true
  path:
    description: Where to unpack the artifact
    required: false
    default: './'
runs:
  using: node12
  main: main.js
