name: Download

on: push

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: |
          sleep 60s
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          workflow: upload.yml
          name: artifact
          path: artifact
      - name: Test
        run: |
          cat artifact/sha | grep ${{github.sha}}
  download-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          workflow: tests.yml
          repo: Homebrew/homebrew-core
          name: bottles
          path: bottles
          pr: 58588
      - name: Test
        run: |
          ls bottles/gofish--0.13.0*.bottle.*
  download-branch:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          workflow: tests.yml
          name: artifact
          path: artifact
          branch: master
      - name: Test
        run: |
          cat artifact/sha | grep ${{github.sha}}