name: Download

on:
  check_run:
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    needs:
      - upload
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download
        uses: ./
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: upload.yml
          commit: ${{github.sha}}
          name: package
          path: ./
      - name: Test
        run: |
          cat file.txt | grep content
