name: Download

on:
  push:
    branches:
      - master

jobs:
  download:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        repo:
          - ''
          - homebrew/linuxbrew-core
        include:
          - repo: homebrew/linuxbrew-core
            workflow: build-bottles.yml
            pr: 19869
            name: bottles
            path: bottles
          - repo: ''
            workflow: upload.yml
            pr: 1
            name: artifact
            path: artifact
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          repo: ${{matrix.repo}}
          workflow: ${{matrix.workflow}}
          pr: ${{matrix.pr}}
          name: ${{matrix.name}}
          path: ${{matrix.path}}
