name: Download

on: push

jobs:
  download:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          workflow: upload.yml
          name: artifact
          path: artifact
      - name: Test
        run: |
          ls artifact/.git/HEAD
