name: Test

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./
  download:
    needs: upload
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          workflow: test.yml
          name: artifact
          path: artifact
      - name: Test
        run: |
          git -C artifact rev-parse HEAD | grep ${{github.sha}}
