name: Upload

on: pull_request

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create
        run: |
          mkdir package
          echo content > package/file.txt
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: package