name: Upload

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: artifact
